# CI Profile - Optimized for continuous integration environments
# Focuses on deterministic behavior and resource efficiency

execution:
  max_agents: 3  # Limited for CI runners
  agent_distribution:
    developer: 2
    reviewer: 1
    shared_pool: 0  # Sequential correction/finalization
  
  timeouts:
    development: 1800000     # 30 minutes
    review: 600000          # 10 minutes  
    correction: 900000      # 15 minutes
    finalization: 300000    # 5 minutes
  
  retry_policy:
    max_attempts: 3
    backoff_multiplier: 2.0
    initial_delay: 10000

quality:
  review_mode: "strict"  # High quality in CI
  
  requirements:
    test_coverage: 85
    documentation_level: "comprehensive"
    linting_strictness: "error"
    
  code_quality:
    max_complexity: 8
    max_file_length: 400
    max_function_length: 40
    
  testing:
    required_test_types:
      - unit
      - integration
      - e2e
    parallel_test_execution: false  # Predictable in CI
    fail_fast: true

git:
  branch_pattern: "ci/task-{id}-{timestamp}"
  commit_style: "conventional"
  squash_commits: true
  rebase_before_merge: true
  
  worktree:
    location: "/tmp/worktrees"  # Use temp directory in CI
    cleanup_strategy: "always"
    preserve_failed: false

automation:
  auto_merge:
    enabled: false  # Manual merge in CI
    method: "squash"
    delete_branch_on_merge: true
    wait_for_checks: true
    
  pr_creation:
    draft_if_wip: true
    add_reviewers: true
    add_labels: true
    
  notifications:
    on_task_complete: false
    on_pr_created: false
    on_errors: true  # Only notify on errors

resource_limits:
  max_disk_usage: 536870912    # 500MB - CI constraint
  max_memory_per_agent: 256    # MB - CI constraint
  max_concurrent_operations: 5
  
monitoring:
  progress_display: "detailed"  # Full logs for CI
  update_interval: 30000       # Less frequent in CI
  log_level: "debug"           # Maximum detail
  
  metrics:
    track_performance: true
    track_quality: true
    generate_reports: true

error_handling:
  recovery_strategy: "conservative"
  checkpoint_frequency: 180000  # 3 minutes
  preserve_on_error: false      # Clean CI environment
  
  escalation:
    critical_errors_threshold: 1  # Fail fast in CI
    auto_rollback: true
    notify_on_critical: true

features:
  parallel_testing: false       # Sequential for determinism
  incremental_builds: false     # Clean builds in CI
  smart_conflict_resolution: true
  dependency_caching: false     # Fresh dependencies
  
integrations:
  task_master:
    auto_update_status: true
    sync_interval: 30000
    
  github:
    use_gh_cli: true
    api_rate_limit_buffer: 200  # Conservative in CI
    
ci_specific:
  environment_validation: true
  dependency_verification: true
  security_scanning: true
  artifact_generation: true
  
  outputs:
    junit_reports: true
    coverage_reports: true
    performance_reports: true
    
  cache:
    enabled: false  # No caching between runs
    
  artifacts:
    preserve_logs: true
    preserve_reports: true
    retention_days: 30