# Conservative Profile - Safe and thorough execution
# Use this profile for production-critical tasks or when stability is paramount

name: conservative
description: "Maximum safety with thorough validation"

# Limit concurrent execution
defaults:
  max_agents: 2              # Only 2 parallel agents
  review_mode: strict        # Strictest review standards
  branch_pattern: "feature/task-{id}-safe"
  
# Enhanced safety features
features:
  auto_cleanup: false        # Manual cleanup only
  auto_retry: false          # No automatic retries
  interactive_conflicts: true # Always interactive
  dry_run_first: true       # Always preview before execution
  
# Conservative timeouts
timeouts:
  agent_idle: 600           # 10 minutes
  task_max: 7200           # 2 hours per task
  review_max: 1800         # 30 minutes for review
  correction_max: 3600     # 1 hour for corrections
  
# Strict quality requirements
quality:
  min_test_coverage: 90     # 90% minimum coverage
  lint_required: true
  format_required: true
  docs_required: true
  changelog_required: true  # Require changelog updates
  
# Enhanced review settings
review_modes:
  strict:
    require_all_tests_pass: true
    require_documentation: true
    require_changelog: true
    require_examples: true
    max_corrections: 2      # Fail after 2 correction cycles
    require_peer_review: true
    
# Conservative resource limits
resources:
  max_memory_mb: 1024      # Lower memory limit
  max_worktrees: 3         # Fewer concurrent worktrees
  cpu_limit_percent: 50    # Use only 50% CPU
  
# Additional safety checks
safety:
  require_clean_working_tree: true
  backup_before_operations: true
  verify_dependencies_twice: true
  extensive_conflict_analysis: true
  
# Detailed logging
logging:
  level: debug             # Maximum verbosity
  include_git_commands: true
  include_file_operations: true
  save_agent_transcripts: true
  
# Conservative git settings
git:
  shallow_clone: false     # Full clones only
  verify_signatures: true  # Verify commit signatures
  protected_branch_check: true
  
# Notification overrides
notifications:
  on_any_warning: true
  on_quality_gate_fail: true
  require_confirmation: true # Require confirmation for critical operations